POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "test user",
  "email": "test6@test.com",
  "password": "#Senha123",
  "profileType": "CORPORATE"
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "joao@test.com",
  "password": "#Senha123"
}
