// user 'Teste Gamification'

GET http://localhost:4000/gamification/ranking?limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODVkYWMxYy1jZjZlLTQzYWUtOGZlZi05ZThjZjc2NGZjMmIiLCJlbWFpbCI6InRlc3RHYW1lQHRlc3QuY29tIiwic2NvcGUiOiJQRVJTT05BTCIsImlhdCI6MTc2ODg2Nzc4NywiZXhwIjoxNzcwMTYzNzg3fQ.WUu95dROB7vDLauoiGHJ95L2nA3voMi8fdhZic-iJPk

###
GET http://localhost:4000/gamification/badges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODVkYWMxYy1jZjZlLTQzYWUtOGZlZi05ZThjZjc2NGZjMmIiLCJlbWFpbCI6InRlc3RHYW1lQHRlc3QuY29tIiwic2NvcGUiOiJQRVJTT05BTCIsImlhdCI6MTc2ODg2Nzc4NywiZXhwIjoxNzcwMTYzNzg3fQ.WUu95dROB7vDLauoiGHJ95L2nA3voMi8fdhZic-iJPk

###
GET http://localhost:4000/gamification/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjM0NGQ0MS1kOGJlLTRlZTgtODkzOC00YTgzMDIyMmE3Y2UiLCJlbWFpbCI6ImpvYW9AdGVzdC5jb20iLCJzY29wZSI6IlBFUlNPTkFMIiwiaWF0IjoxNzY5ODMyNDk4LCJleHAiOjE3NzExMjg0OTh9.WeP2KSQc6gzxN1ouCV1Xnub7NjlMs2dPrETFGZWJEao
